//------------------------------------------------------------------------------
// <auto-generated>
//     This code was manually created for localization support.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Resources;
using System.Globalization;

namespace TILSOFTAI.Domain.Properties
{
    public static class Resources
    {
        private static readonly Lazy<ResourceManager> _resourceManager = new(() =>
            new ResourceManager("TILSOFTAI.Domain.Properties.Resources", typeof(Resources).Assembly));

        private static ResourceManager ResourceManager => _resourceManager.Value;

        // Validation Messages  
        public static string Val_ToolNameRequired => ResourceManager.GetString(nameof(Val_ToolNameRequired))!;
        public static string Val_HandlerTypeMustImplementIToolHandler => ResourceManager.GetString(nameof(Val_HandlerTypeMustImplementIToolHandler))!;
        public static string Val_ToolDefinitionNameRequired => ResourceManager.GetString(nameof(Val_ToolDefinitionNameRequired))!;
        public static string Val_ToolDefinitionInstructionRequired => ResourceManager.GetString(nameof(Val_ToolDefinitionInstructionRequired))!;
        public static string Val_ToolDefinitionJsonSchemaRequired => ResourceManager.GetString(nameof(Val_ToolDefinitionJsonSchemaRequired))!;
        public static string Val_ToolDefinitionSpNameMustStartWithAi => ResourceManager.GetString(nameof(Val_ToolDefinitionSpNameMustStartWithAi))!;
        public static string Val_ArgumentsJsonRequired => ResourceManager.GetString(nameof(Val_ArgumentsJsonRequired))!;
        public static string Val_MissingRequiredProperty => ResourceManager.GetString(nameof(Val_MissingRequiredProperty))!;
        public static string Val_PropertyMustBeIntegerGreaterThanOne => ResourceManager.GetString(nameof(Val_PropertyMustBeIntegerGreaterThanOne))!;
        public static string Val_PropertyMustBeArray => ResourceManager.GetString(nameof(Val_PropertyMustBeArray))!;
        public static string Val_PropertyMustContainIntegersGreaterThanOne => ResourceManager.GetString(nameof(Val_PropertyMustContainIntegersGreaterThanOne))!;
        public static string Val_PropertyMustContainMinimumItems => ResourceManager.GetString(nameof(Val_PropertyMustContainMinimumItems))!;
        public static string Val_StoredProcedureRequired => ResourceManager.GetString(nameof(Val_StoredProcedureRequired))!;
        public static string Val_ProposedSpNameRequired => ResourceManager.GetString(nameof(Val_ProposedSpNameRequired))!;
        public static string Val_SchemaValidationFailed => ResourceManager.GetString(nameof(Val_SchemaValidationFailed))!;
        public static string Val_ArgumentsMustBeValidJson => ResourceManager.GetString(nameof(Val_ArgumentsMustBeValidJson))!;
        public static string Val_SchemaValidationFailedAtExecutionTime => ResourceManager.GetString(nameof(Val_SchemaValidationFailedAtExecutionTime))!;
        public static string Val_QueryRequiredForCatalogSearch => ResourceManager.GetString(nameof(Val_QueryRequiredForCatalogSearch))!;
        public static string Val_DatasetKeyRequiredForCatalogGetDataset => ResourceManager.GetString(nameof(Val_DatasetKeyRequiredForCatalogGetDataset))!;
        public static string Val_PlanJsonRequiredForAnalyticsValidatePlan => ResourceManager.GetString(nameof(Val_PlanJsonRequiredForAnalyticsValidatePlan))!;
        public static string Val_IdRequired => ResourceManager.GetString(nameof(Val_IdRequired))!;
        public static string Val_EventNameRequired => ResourceManager.GetString(nameof(Val_EventNameRequired))!;
        public static string Val_JwksAddressRequired => ResourceManager.GetString(nameof(Val_JwksAddressRequired))!;
        public static string Val_RequestBodyRequired => ResourceManager.GetString(nameof(Val_RequestBodyRequired))!;
        public static string Val_MessagesRequired => ResourceManager.GetString(nameof(Val_MessagesRequired))!;
        public static string Val_LastMessageMustBeUserMessage => ResourceManager.GetString(nameof(Val_LastMessageMustBeUserMessage))!;
        public static string Val_AtLeastOneUserMessageRequired => ResourceManager.GetString(nameof(Val_AtLeastOneUserMessageRequired))!;
        public static string Val_ModuleArgumentRequired => ResourceManager.GetString(nameof(Val_ModuleArgumentRequired))!;
        public static string Val_RuleKeyArgumentRequired => ResourceManager.GetString(nameof(Val_RuleKeyArgumentRequired))!;
        public static string Val_ProposedToolNameArgumentRequired => ResourceManager.GetString(nameof(Val_ProposedToolNameArgumentRequired))!;
        public static string Val_ProposedSpNameArgumentRequired => ResourceManager.GetString(nameof(Val_ProposedSpNameArgumentRequired))!;
        public static string Val_ArgsJsonArgumentRequired => ResourceManager.GetString(nameof(Val_ArgsJsonArgumentRequired))!;
        public static string Val_PlanJsonRequired => ResourceManager.GetString(nameof(Val_PlanJsonRequired))!;

        // Exception Messages
        public static string Ex_ToolAlreadyRegistered => ResourceManager.GetString(nameof(Ex_ToolAlreadyRegistered))!;
        public static string Ex_ToolAlreadyRegisteredWithDifferentHandler => ResourceManager.GetString(nameof(Ex_ToolAlreadyRegisteredWithDifferentHandler))!;
        public static string Ex_PlanValidationFailed => ResourceManager.GetString(nameof(Ex_PlanValidationFailed))!;
        public static string Ex_WriteActionsMustNotExecuteAiStoredProcedures => ResourceManager.GetString(nameof(Ex_WriteActionsMustNotExecuteAiStoredProcedures))!;
        public static string Ex_WriteActionNotAllowedOrNotFound => ResourceManager.GetString(nameof(Ex_WriteActionNotAllowedOrNotFound))!;
        public static string Ex_WriteActionCurrentlyDisabled => ResourceManager.GetString(nameof(Ex_WriteActionCurrentlyDisabled))!;
        public static string Ex_ActionRequestNotFound => ResourceManager.GetString(nameof(Ex_ActionRequestNotFound))!;
        public static string Ex_ActionRequestMustBeApproved => ResourceManager.GetString(nameof(Ex_ActionRequestMustBeApproved))!;
        public static string Ex_WriteActionNoLongerAllowed => ResourceManager.GetString(nameof(Ex_WriteActionNoLongerAllowed))!;
        public static string Ex_WriteActionHasBeenDisabled => ResourceManager.GetString(nameof(Ex_WriteActionHasBeenDisabled))!;
        public static string Ex_ToolSpNameRequired => ResourceManager.GetString(nameof(Ex_ToolSpNameRequired))!;
        public static string Ex_DiagnosticsToolHandlerCanOnlyExecuteAiDiagnosticsRun => ResourceManager.GetString(nameof(Ex_DiagnosticsToolHandlerCanOnlyExecuteAiDiagnosticsRun))!;
        public static string Ex_DiagnosticsArgumentsFailedSchemaValidation => ResourceManager.GetString(nameof(Ex_DiagnosticsArgumentsFailedSchemaValidation))!;
        public static string Ex_DiagnosticsRequiresModuleAndRuleKey => ResourceManager.GetString(nameof(Ex_DiagnosticsRequiresModuleAndRuleKey))!;
        public static string Ex_ExecutionContextTenantIdRequired => ResourceManager.GetString(nameof(Ex_ExecutionContextTenantIdRequired))!;
        public static string Ex_AtomicExecutePlanToolHandlerCanOnlyExecuteAiAtomicExecutePlan => ResourceManager.GetString(nameof(Ex_AtomicExecutePlanToolHandlerCanOnlyExecuteAiAtomicExecutePlan))!;
        public static string Ex_AtomicExecutePlanArgumentsFailedSchemaValidation => ResourceManager.GetString(nameof(Ex_AtomicExecutePlanArgumentsFailedSchemaValidation))!;
        public static string Ex_ExecutionContextTenantIdRequiredToResolveTools => ResourceManager.GetString(nameof(Ex_ExecutionContextTenantIdRequiredToResolveTools))!;
        public static string Ex_ToolDoesNotSpecifySpName => ResourceManager.GetString(nameof(Ex_ToolDoesNotSpecifySpName))!;
        public static string Ex_ConnectionStringNotFoundForTenant => ResourceManager.GetString(nameof(Ex_ConnectionStringNotFoundForTenant))!;
        public static string Ex_ConnectionStringNotFoundForTenantInMetadata => ResourceManager.GetString(nameof(Ex_ConnectionStringNotFoundForTenantInMetadata))!;
        public static string Ex_AzureKeyVaultUriRequired => ResourceManager.GetString(nameof(Ex_AzureKeyVaultUriRequired))!;
        public static string Ex_SqlContractValidationFailed => ResourceManager.GetString(nameof(Ex_SqlContractValidationFailed))!;
        public static string Ex_ErrorCatalogCoverageCheckFailed => ResourceManager.GetString(nameof(Ex_ErrorCatalogCoverageCheckFailed))!;
        public static string Ex_EmbeddingRequestFailed => ResourceManager.GetString(nameof(Ex_EmbeddingRequestFailed))!;
        public static string Ex_EmbeddingResponseContainedNoData => ResourceManager.GetString(nameof(Ex_EmbeddingResponseContainedNoData))!;
        public static string Ex_LlmRequestFailed => ResourceManager.GetString(nameof(Ex_LlmRequestFailed))!;
        public static string Ex_LlmEndpointRequired => ResourceManager.GetString(nameof(Ex_LlmEndpointRequired))!;
        public static string Ex_LlmApiKeyRequired => ResourceManager.GetString(nameof(Ex_LlmApiKeyRequired))!;
        public static string Ex_LlmModelRequired => ResourceManager.GetString(nameof(Ex_LlmModelRequired))!;
        public static string Ex_ExecutionContextConversationIdRequired => ResourceManager.GetString(nameof(Ex_ExecutionContextConversationIdRequired))!;
        public static string Ex_ExecutionContextUserIdRequired => ResourceManager.GetString(nameof(Ex_ExecutionContextUserIdRequired))!;
        public static string Ex_TenantIdRequired => ResourceManager.GetString(nameof(Ex_TenantIdRequired))!;
    }
}
